// File generated by FlutterFire CLI.
// This is a template file. You need to run 'flutterfire configure' to generate actual values.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocRI8iEcqVJoi7To5qpGq27JBMTouJ3E',
    appId: '1:376768263574:web:a18c934f0e444804fd99b7',
    messagingSenderId: '376768263574',
    projectId: 'circlet-9ee47',
    authDomain: 'circlet-9ee47.firebaseapp.com',
    storageBucket: 'circlet-9ee47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMA2ptMxesVbbhAjkb1nq5n7Njerho1WU',
    appId: '1:376768263574:android:67876195466d3dbcfd99b7',
    messagingSenderId: '376768263574',
    projectId: 'circlet-9ee47',
    storageBucket: 'circlet-9ee47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdAZEBYD-ZKxyAPJ9o6-dH47cZ1BZdUk',
    appId: '1:376768263574:ios:093a5c038fa693b1fd99b7',
    messagingSenderId: '376768263574',
    projectId: 'circlet-9ee47',
    storageBucket: 'circlet-9ee47.firebasestorage.app',
    iosBundleId: 'com.circlet.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.Circlet.Circlet',
  );
}
